In [1]:
#Import Library
import numpy as np

# Dataset
Used the Bank Authentication Data Set to start off with. This data set consists of various image features derived from images that had 400 x 400 pixels.The data itself that we will be using ARE NOT ACTUAL IMAGES, they are features of images. 
More info on the data set:

https://archive.ics.uci.edu/ml/datasets/banknote+authentication

Data were extracted from images that were taken from genuine and forged banknote-like specimens. For digitization, an industrial camera usually used for print inspection was used. The final images have 400x 400 pixels. Due to the object lens and distance to the investigated object gray-scale pictures with a resolution of about 660 dpi were gained. Wavelet Transform tool were used to extract features from images.

Attribute Information:

variance of Wavelet Transformed image (continuous)
skewness of Wavelet Transformed image (continuous)
curtosis of Wavelet Transformed image (continuous)
entropy of image (continuous)
class (integer)


In [2]:
#Reading the Data
from numpy import genfromtxt
data = genfromtxt('../DATA/bank_note_data.txt', delimiter=',')

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
#Explore Features and Labels
labels=data[:,4]

In [5]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [8]:
features=data[:,0:4]

In [9]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [10]:
X=features
y=labels

# Split the Data into Training and Test
split the data into a train/test set using sklearn

In [11]:
#Spliting Data into Training and testing set

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

In [14]:
len(X_train)

919

In [15]:
len(X)

1372

# Standardizing the Data
standardize the data to get better performance using Neural Networks.Standardization means normalizing the values to all fit between a certain range, like 0-1, or -1 to 1.

The scikit learn library also provides a nice function for this.

http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html

In [17]:
from sklearn.preprocessing import MinMaxScaler


In [18]:
scaler_object=MinMaxScaler()

In [19]:
#Fitting scaler on training data(find min and max values)
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [20]:
scaled_X_train=scaler_object.transform(X_train)

In [21]:
scaled_X_test=scaler_object.transform(X_test)

In [22]:
scaled_X_train.max()

1.0000000000000002

# Building the Network with Keras
Let's build a simple neural network!

In [24]:
from keras.models import Sequential
from keras.layers import Dense

In [26]:
#create model
model=Sequential()
#Input layer
model.add(Dense(4,input_dim=4,activation='relu'))
#Middle layer(add another dense layer)
model.add(Dense(8,activation='relu'))
#Output layer(0 0r 1)
model.add(Dense(1,activation='sigmoid'))


In [27]:
#Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [30]:
#Train the model
model.fit(scaled_X_train,y_train,epochs=50, verbose=2)

Epoch 1/50
 - 0s - loss: 0.3702 - accuracy: 0.8705
Epoch 2/50
 - 0s - loss: 0.3626 - accuracy: 0.8770
Epoch 3/50
 - 0s - loss: 0.3559 - accuracy: 0.8857
Epoch 4/50
 - 0s - loss: 0.3486 - accuracy: 0.8814
Epoch 5/50
 - 0s - loss: 0.3443 - accuracy: 0.8966
Epoch 6/50
 - 0s - loss: 0.3354 - accuracy: 0.8912
Epoch 7/50
 - 0s - loss: 0.3274 - accuracy: 0.9010
Epoch 8/50
 - 0s - loss: 0.3204 - accuracy: 0.9086
Epoch 9/50
 - 0s - loss: 0.3136 - accuracy: 0.9119
Epoch 10/50
 - 0s - loss: 0.3064 - accuracy: 0.9184
Epoch 11/50
 - 0s - loss: 0.3002 - accuracy: 0.9206
Epoch 12/50
 - 0s - loss: 0.2929 - accuracy: 0.9249
Epoch 13/50
 - 0s - loss: 0.2868 - accuracy: 0.9314
Epoch 14/50
 - 0s - loss: 0.2805 - accuracy: 0.9325
Epoch 15/50
 - 0s - loss: 0.2737 - accuracy: 0.9402
Epoch 16/50
 - 0s - loss: 0.2675 - accuracy: 0.9402
Epoch 17/50
 - 0s - loss: 0.2618 - accuracy: 0.9423
Epoch 18/50
 - 0s - loss: 0.2556 - accuracy: 0.9445
Epoch 19/50
 - 0s - loss: 0.2504 - accuracy: 0.9456
Epoch 20/50
 - 0s - l

In [31]:
model.predict(scaled_X_test)

array([[2.90048718e-02],
       [4.38106775e-01],
       [2.49689549e-01],
       [2.07172334e-02],
       [2.66330838e-02],
       [1.12793148e-02],
       [8.83082747e-02],
       [5.20208478e-03],
       [1.85372233e-02],
       [4.70302701e-02],
       [6.01858974e-01],
       [8.64392102e-01],
       [5.46897948e-02],
       [8.10199499e-01],
       [2.80939698e-01],
       [3.85973006e-01],
       [8.64392102e-01],
       [8.64392102e-01],
       [7.84823060e-01],
       [8.16724062e-01],
       [1.44496858e-02],
       [2.78442502e-02],
       [8.46602678e-01],
       [8.99374485e-03],
       [8.64392102e-01],
       [1.07272565e-02],
       [4.55096364e-03],
       [8.64392102e-01],
       [2.87532806e-04],
       [1.19861960e-03],
       [8.63997221e-01],
       [4.42237556e-02],
       [7.78888166e-02],
       [8.64392102e-01],
       [8.64392102e-01],
       [4.54828143e-03],
       [5.64492464e-01],
       [8.62422943e-01],
       [8.64392102e-01],
       [3.56506109e-02],


In [33]:
#model.predict_classes(scaled_X_test)

In [34]:
#Evaluating model metrics
model.metrics_names

['loss', 'accuracy']

In [46]:
model.evaluate(x=scaled_X_test,y=y_test)

453/453 [==============================] - 0s 117us/step


[0.13673589904083322, 0.9757174253463745]

In [36]:
from sklearn.metrics import confusion_matrix,classification_report

In [41]:
predictions=model.predict_classes(scaled_X_test)

In [42]:
confusion_matrix(y_test,predictions)

array([[256,   1],
       [ 10, 186]], dtype=int64)

In [43]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

         0.0       0.96      1.00      0.98       257
         1.0       0.99      0.95      0.97       196

    accuracy                           0.98       453
   macro avg       0.98      0.97      0.98       453
weighted avg       0.98      0.98      0.98       453



In [44]:
#saving Model
model.save('kerasmodel.h5')